// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCo_iZeW6HldJZMcCWEjGbq9BZMfgLqSc',
    appId: '1:1082239247849:web:e2714069c06c8cc8f91778',
    messagingSenderId: '1082239247849',
    projectId: 'atomic-elixir-310108',
    authDomain: 'atomic-elixir-310108.firebaseapp.com',
    storageBucket: 'atomic-elixir-310108.appspot.com',
    measurementId: 'G-3KWZJJ6VQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnOXrhefpdQhvJYF6ysmwsKnZSKrVf7vM',
    appId: '1:1082239247849:android:0a3c0b81aeeaad94f91778',
    messagingSenderId: '1082239247849',
    projectId: 'atomic-elixir-310108',
    storageBucket: 'atomic-elixir-310108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9A2MZsobaIt2rkO74wCmI8MR_hdn2T88',
    appId: '1:1082239247849:ios:a777f02c68af2a44f91778',
    messagingSenderId: '1082239247849',
    projectId: 'atomic-elixir-310108',
    storageBucket: 'atomic-elixir-310108.appspot.com',
    iosClientId: '1082239247849-98vrgs5d1qc268q119vc7k45du9fuf2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.pub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9A2MZsobaIt2rkO74wCmI8MR_hdn2T88',
    appId: '1:1082239247849:ios:a9435947fcca4618f91778',
    messagingSenderId: '1082239247849',
    projectId: 'atomic-elixir-310108',
    storageBucket: 'atomic-elixir-310108.appspot.com',
    iosClientId: '1082239247849-hna00obmjtb3m2ptuhooov319dh1rt4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pub.RunnerTests',
  );
}
